export interface PLPProduct {
  id: number
  name: string
  priceEUR: number
  priceCFA: number
  imageA: string
  imageB: string
  matiere: string
  tailles: string[]
  couleur: string
  couleurHex: string
  isNew: boolean
  createdAt: number
}

export const MATIERES = [
  "Bazin Riche",
  "Wax Premium",
  "Lin",
  "Soie",
  "Pagne Manjak",
] as const

export const TAILLES = ["36", "38", "40", "42", "44", "Sur-Mesure"] as const

export const COULEURS = [
  { name: "Terracotta", hex: "#A0522D" },
  { name: "Indigo", hex: "#2C3E6B" },
  { name: "Ivoire", hex: "#FFFFF0" },
  { name: "Emeraude", hex: "#2E6B4F" },
  { name: "Bordeaux", hex: "#6B2142" },
  { name: "Or", hex: "#D4AF37" },
  { name: "Noir", hex: "#1C1917" },
  { name: "Vert Sauge", hex: "#87A68C" },
] as const

export const SORT_OPTIONS = [
  { label: "Pertinence", value: "relevance" },
  { label: "Nouveautés", value: "newest" },
  { label: "Prix croissant", value: "price-asc" },
  { label: "Prix décroissant", value: "price-desc" },
] as const

export const ALL_PRODUCTS: PLPProduct[] = [
  {
    id: 1,
    name: "Robe Kebe - Bazin Brode",
    priceEUR: 185,
    priceCFA: 120000,
    imageA: "/images/product-1a.jpg",
    imageB: "/images/product-1b.jpg",
    matiere: "Bazin Riche",
    tailles: ["36", "38", "40", "42"],
    couleur: "Terracotta",
    couleurHex: "#A0522D",
    isNew: true,
    createdAt: 8,
  },
  {
    id: 2,
    name: "Ensemble Ndiaye - Indigo Royal",
    priceEUR: 245,
    priceCFA: 160000,
    imageA: "/images/product-2a.jpg",
    imageB: "/images/product-2b.jpg",
    matiere: "Bazin Riche",
    tailles: ["38", "40", "42", "44"],
    couleur: "Indigo",
    couleurHex: "#2C3E6B",
    isNew: true,
    createdAt: 7,
  },
  {
    id: 3,
    name: "Robe Diop - Soie Manjak",
    priceEUR: 310,
    priceCFA: 205000,
    imageA: "/images/product-3a.jpg",
    imageB: "/images/product-3b.jpg",
    matiere: "Pagne Manjak",
    tailles: ["36", "38", "40"],
    couleur: "Ivoire",
    couleurHex: "#FFFFF0",
    isNew: false,
    createdAt: 6,
  },
  {
    id: 4,
    name: "Tailleur Sall - Emeraude",
    priceEUR: 275,
    priceCFA: 180000,
    imageA: "/images/product-4a.jpg",
    imageB: "/images/product-4b.jpg",
    matiere: "Bazin Riche",
    tailles: ["38", "40", "42", "44", "Sur-Mesure"],
    couleur: "Emeraude",
    couleurHex: "#2E6B4F",
    isNew: false,
    createdAt: 5,
  },
  {
    id: 5,
    name: "Robe Faye - Bordeaux Dore",
    priceEUR: 220,
    priceCFA: 145000,
    imageA: "/images/product-5a.jpg",
    imageB: "/images/product-5b.jpg",
    matiere: "Bazin Riche",
    tailles: ["36", "38", "40", "42"],
    couleur: "Bordeaux",
    couleurHex: "#6B2142",
    isNew: true,
    createdAt: 4,
  },
  {
    id: 6,
    name: "Robe Ba - Soiree Or",
    priceEUR: 395,
    priceCFA: 260000,
    imageA: "/images/product-6a.jpg",
    imageB: "/images/product-6b.jpg",
    matiere: "Soie",
    tailles: ["36", "38", "40"],
    couleur: "Or",
    couleurHex: "#D4AF37",
    isNew: true,
    createdAt: 3,
  },
  {
    id: 7,
    name: "Ensemble Gueye - Wax Nuit",
    priceEUR: 265,
    priceCFA: 175000,
    imageA: "/images/product-7a.jpg",
    imageB: "/images/product-7b.jpg",
    matiere: "Wax Premium",
    tailles: ["38", "40", "42", "44"],
    couleur: "Noir",
    couleurHex: "#1C1917",
    isNew: false,
    createdAt: 2,
  },
  {
    id: 8,
    name: "Ensemble Sarr - Lin Manjak",
    priceEUR: 195,
    priceCFA: 128000,
    imageA: "/images/product-8a.jpg",
    imageB: "/images/product-8b.jpg",
    matiere: "Lin",
    tailles: ["36", "38", "40", "42", "Sur-Mesure"],
    couleur: "Vert Sauge",
    couleurHex: "#87A68C",
    isNew: false,
    createdAt: 1,
  },
  {
    id: 9,
    name: "Robe Diouf - Bazin Solaire",
    priceEUR: 210,
    priceCFA: 138000,
    imageA: "/images/product-1a.jpg",
    imageB: "/images/product-1b.jpg",
    matiere: "Bazin Riche",
    tailles: ["36", "38", "40", "42", "44"],
    couleur: "Terracotta",
    couleurHex: "#A0522D",
    isNew: false,
    createdAt: 0,
  },
  {
    id: 10,
    name: "Robe Sow - Soie Indigo",
    priceEUR: 340,
    priceCFA: 225000,
    imageA: "/images/product-2a.jpg",
    imageB: "/images/product-2b.jpg",
    matiere: "Soie",
    tailles: ["36", "38", "40"],
    couleur: "Indigo",
    couleurHex: "#2C3E6B",
    isNew: true,
    createdAt: 9,
  },
  {
    id: 11,
    name: "Ensemble Mbaye - Wax Emeraude",
    priceEUR: 255,
    priceCFA: 168000,
    imageA: "/images/product-4a.jpg",
    imageB: "/images/product-4b.jpg",
    matiere: "Wax Premium",
    tailles: ["38", "40", "42"],
    couleur: "Emeraude",
    couleurHex: "#2E6B4F",
    isNew: false,
    createdAt: -1,
  },
  {
    id: 12,
    name: "Robe Thiam - Lin Ivoire",
    priceEUR: 175,
    priceCFA: 115000,
    imageA: "/images/product-3a.jpg",
    imageB: "/images/product-3b.jpg",
    matiere: "Lin",
    tailles: ["36", "38", "40", "42", "44", "Sur-Mesure"],
    couleur: "Ivoire",
    couleurHex: "#FFFFF0",
    isNew: false,
    createdAt: -2,
  },
]
